<?php

return array(
    'pickup' => array(
        'type' => 'store_pickup',
        'value' => 'Recoge en tienda',
        'label' => 'Recoge en tienda',
        'shipping' => 0.00,
        'address' => '8A Avenida 19-55, Ciudad de Guatemala 01001',
        'schedule' => 'Lunes a viernes de 8:00 am a 5:30 pm y sábado de 8:00 am a 1:00 pm.',
    ),
    'shipping_groups' => array(
        'Ciudad de Guatemala' => array(
            'Ciudad de Guatemala, Zona 1' => 25.00,
            'Ciudad de Guatemala, Zona 2' => 25.00,
            'Ciudad de Guatemala, Zona 3' => 25.00,
            'Ciudad de Guatemala, Zona 4' => 25.00,
            'Ciudad de Guatemala, Zona 5' => 25.00,
            'Ciudad de Guatemala, Zona 6' => 25.00,
            'Ciudad de Guatemala, Zona 7' => 25.00,
            'Ciudad de Guatemala, Zona 8' => 25.00,
            'Ciudad de Guatemala, Zona 9' => 25.00,
            'Ciudad de Guatemala, Zona 10' => 25.00,
            'Ciudad de Guatemala, Zona 11' => 25.00,
            'Ciudad de Guatemala, Zona 12' => 25.00,
            'Ciudad de Guatemala, Zona 13' => 25.00,
            'Ciudad de Guatemala, Zona 14' => 25.00,
            'Ciudad de Guatemala, Zona 15' => 25.00,
            'Ciudad de Guatemala, Zona 16' => 30.00,
            'Ciudad de Guatemala, Zona 17' => 30.00,
            'Ciudad de Guatemala, Zona 18' => 30.00,
            'Ciudad de Guatemala, Zona 19' => 30.00,
            'Ciudad de Guatemala, Zona 21' => 30.00,
            'Ciudad de Guatemala, Zona 24' => 35.00,
            'Ciudad de Guatemala, Zona 25' => 35.00,
        ),
        'Mixco' => array(
            'Mixco, Zona 1' => 35.00,
            'Mixco, Zona 2' => 35.00,
            'Mixco, Zona 3' => 30.00,
            'Mixco, Zona 4' => 30.00,
            'Mixco, Zona 5' => 30.00,
            'Mixco, Zona 6' => 30.00,
            'Mixco, Zona 7' => 35.00,
            'Mixco, Zona 8' => 35.00,
            'Mixco, Zona 9' => 40.00,
            'Mixco, Zona 10' => 30.00,
            'Mixco, Zona 11' => 35.00,
        ),
        'Villa Nueva' => array(
            'Villa Nueva, Zona 1' => 35.00,
            'Villa Nueva, Zona 2' => 35.00,
            'Villa Nueva, Zona 3' => 35.00,
            'Villa Nueva, Zona 4' => 35.00,
            'Villa Nueva, Zona 5' => 35.00,
            'Villa Nueva, Zona 6' => 35.00,
            'Villa Nueva, Zona 8' => 35.00,
            'Villa Nueva, Zona 10' => 35.00,
            'Villa Nueva, Zona 11' => 35.00,
            'Villa Nueva, Zona 12' => 35.00,
        ),
        'Otros lugares' => array(
            'Boca del Monte' => 40.00,
            'San Miguel Petapa' => 40.00,
            'Ciudad Quetzal' => 70.00,
            'Departamentos' => 50.00,
        ),
    ),
);
